"""Shared data models for inter-agent communication.

The Unit 6 design separates responsibilities across specialised logical roles.
Using explicit Pydantic models at those boundaries reduces the risk of stale,
mis-associated, or malformed state being passed between stages of the workflow.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, HttpUrl


class StepStatus(str, Enum):
    """Execution state for a planned research step."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class ResearchGoal(BaseModel):
    """High-level goal supplied by the user."""

    topic: str = Field(min_length=3)
    objective: Optional[str] = None


class ResearchSubtask(BaseModel):
    """One searchable sub-question generated by the planner."""

    id: str = Field(min_length=1)
    question: str = Field(min_length=5)
    search_terms: List[str] = Field(min_length=1)
    status: StepStatus = StepStatus.PENDING
    retry_count: int = Field(default=0, ge=0)


class ResearchPlan(BaseModel):
    """Inspectable plan produced before retrieval begins."""

    goal: ResearchGoal
    subtasks: List[ResearchSubtask] = Field(min_length=1)
    rationale: Optional[str] = None


class AcademicRecord(BaseModel):
    """Normalised scholarly metadata returned by retrieval tools."""

    title: str
    authors: List[str] = Field(default_factory=list)
    year: Optional[int] = None
    doi: Optional[str] = None
    source: str
    url: Optional[HttpUrl] = None
    abstract: Optional[str] = None


class ScoredRecord(BaseModel):
    """Retrieved record after deterministic relevance scoring."""

    record: AcademicRecord
    relevance_score: float = Field(ge=0.0, le=1.0)


class RankedEvidence(BaseModel):
    """Evidence item after processing, ranking, and summarisation."""

    record: AcademicRecord
    relevance_score: float = Field(ge=0.0, le=1.0)
    summary: str
    traceable: bool = False


class ValidationResult(BaseModel):
    """Outcome from the evidence validation stage."""

    passed: bool
    issues: List[str] = Field(default_factory=list)
    retry_target: Optional[str] = None


class AgentState(BaseModel):
    """Shared state carried through the planning workflow."""

    goal: ResearchGoal
    plan: Optional[ResearchPlan] = None
    retrieved_records: List[AcademicRecord] = Field(default_factory=list)
    scored_records: List[ScoredRecord] = Field(default_factory=list)
    ranked_evidence: List[RankedEvidence] = Field(default_factory=list)
    validation: Optional[ValidationResult] = None
    approved_for_export: bool = False
